resources:
  - name: egest-repository
    type: git
    source:
      uri: {{git_url}} 
      branch: {{branch}}
      paths: 
        - takeon-dbexport/
      tag_filter: v*

  - name: ecr-image-egest
    type: docker-image
    source:
      repository: {{ecr_repo}}
      tag: egestion
      aws_access_key_id: ((aws.aws_((aws_key_prefix))_access_key))
      aws_secret_access_key: ((aws.aws_((aws_key_prefix))_secret_access_key))

jobs:
  - name: installing-dependencies-egest
    plan:
      - get: egest-repository
        trigger: true
      - put: ecr-image-egest
        params:
          build: egest-repository/takeon-dbexport
          tag_as_latest: false