resources:
  # - name: base-go-image
  #   type: docker-image
  #   source:
  #     repository: golang
  #     tag: 1.13.4-stretch

  # - name: egest-repository-main
  #   type: git
  #   source:
  #     uri: https://github.com/ONSdigital/takeon-egest-pipeline.git
  #     branch: feature/LU-5452-egestPipeline

  - name: egest-repository
    type: git
    source:
      uri: https://github.com/ONSdigital/takeon-egest-pipeline.git
      branch: feature/LU-5452-egestPipeline
      paths: 
        - takeon-dbexport/

  - name: ecr-image-egest
    type: docker-image
    source:
      repository: 226575302242.dkr.ecr.eu-west-2.amazonaws.com/takeon-validation-cicd
      tag: egestion
      aws_access_key_id: ((aws.aws_access_key))
      aws_secret_access_key: ((aws.aws_secret_access_key))

jobs:
  - name: installing-dependencies-egest
    plan:
      - get: egest-repository
        trigger: true
      - put: ecr-image-egest
        params:
          build: egest-repository/takeon-dbexport
          tag_as_latest: false
      # - in_parallel:
      #   - get: egest-repository-main
      #   # - get: egest-repository
      #     trigger: true

      #   - get: base-go-image
      #     params:
      #       save: true

      # - put: ecr-image-egest
      #   params:
      #     load_base: base-go-image
      #     build: egest-repository